### PR TITLE
Add root Cargo.toml

### PR DESCRIPTION
**Pull request by vivianjeng**
Let the package can be imported by
```toml
# Cargo.toml
# ...
expander_compiler = { git = "https://github.com/PolyhedraZK/ExpanderCompilerCollection" }
```

### CODE REVIEW

**Comment by siq1** [comment]
Thank you for your pull request. However, I can import the package successfully on my local environment without any modifications.

Could you please let me know the versions of Rust and Cargo you are using? Thank you.

**Comment by vivianjeng** [comment]
I used `cargo 1.82.0-nightly (8f40fc59f 2024-08-21)`
could you try to remove the `target/`? thank you 🙏🏻

**Comment by vivianjeng** [comment]
I write an example to import the package
https://github.com/vivianjeng/expander-rs-keccak256/blob/e8c781c23f4b7309fd9d57ba06132734648d5762/Cargo.toml#L23
and fix the `clippy` errors
https://github.com/vivianjeng/ExpanderCompilerCollection/pull/1

**Review by siq1 — APPROVED** [review]

**Comment by siq1** [comment]
Your pull request will first be merged into the dev branch, and then it will be merged into the master branch next Monday.

**Pull request merged**
